export const planes = [
  {
    id: 1,
    nombre_plan: "Plan Básico",
    precio_plan: 5,
    titulo: " Paga por 1 mes",
    descripcion: "*30 días de contenido exclusivo",
    color_card: "#FFEE97",
    color_principal: "#FFE251",
    color_text: "#8A8A8A",
    ruta_img: "/planes/planB.png",
    flow_plan_id: "plan_basico_1",
  },
  {
    id: 2,
    nombre_plan: "Plan Estándar",
    precio_plan: 27,
    titulo: " Paga por 6 meses y ahorra 10%",
    descripcion: "*precio regular $30USD",
    color_card: "#C3F3F3",
    color_principal: "#68E1E0",
    color_text: "#8A8A8A",
    ruta_img: "/planes/planE.png",
    flow_plan_id: "plan_estandar",
  },
  {
    id: 3,
    nombre_plan: "Plan Pro Crafter",
    precio_plan: 55,
    titulo: "Paga una vez al año",
    descripcion: "*precio regular $60USD",
    color_card: "#FFB4DF",
    color_principal: "#FC68B9",
    color_text: "#ffffff",
    ruta_img: "/planes/planPro.png",
    flow_plan_id: "plan_pro",
  },
];
